/**
 * checkin | Error | Code | |
 * ----------------------------------------------------------------------
 * | - | | checkInCodePrefix | 4155 | | invalidObjectID | 1 | |
 * invalidMiddlewareContext | 2 | | customDatabaseError | 3 | |
 * codeControllerError | 4 | | decodeBody | 5 | | invalidParameter
 * | 6 | | integrationError | 7 | | cannotSendSSE | 8 |
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator
 * program. https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.rockspoon.merchant.datasource.rockspoon_merchant.checkin.models

/**
 * @param deviceId Device ID in which the check-in took place
 * @param distance Distance representation of the beacon and correlates to
 *     the strength of the beacon signal
 */
data class InlineResponse200Devices(
    /** Device ID in which the check-in took place */
    val deviceId: String? = null,
    /**
     * Distance representation of the beacon and correlates to the strength of
     * the beacon signal
     */
    val distance: java.math.BigDecimal? = null
)

